- pandas 所包含的数据结构和数据处理工具的设计使得在 Python 中进行数据清洗和分析非常快捷
- pandas 经常和其它数值计算工具，比如 NumPy 和 SciPy, 以及数据可视化工具，比如 matplotlib 一起使用的
- pandas 和 NumPy 的不同之处：pandas 是用来处理表格型或异质型数据的， 而 NumPy 更适合处理同质型的数值类数组数据

In [1]:
import pandas as pd
from pandas import Series, DataFrame

# 5.1 pandas 数据结构介绍

## 5.1.1 Series

In [2]:
# 最简单的序列可以仅仅由一个数组形成
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [9]:
# 使用字典生成一个 Series
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [12]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [14]:
# pandas 使用isnull 和 notnull 函数来检查缺失数据
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [15]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [16]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [18]:
# Chp 7 中将深入讨论处理缺失数据的细节
# 在数学操作中自动对齐索引是 Series 的一个非常有用的特性
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [19]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [20]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [21]:
# Series 对象自身和其索引都有 name 属性， 这个特性与 pandas 其它重要功能集成在一起
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [22]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [23]:
# Series 的索引可以通过位置赋值的方式进行改变
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [24]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## 5.1.2 DataFrame

In [27]:
# 构建DataFrame，常用方式：利用包含 等长度列表或NumPy数组 的字典来形成 DataFrame
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [28]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [29]:
# 若指定列的顺序， DataFrame 的列将会按照指定顺序排列
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [30]:
# 如果传的列不包含在字典中，将会在结果中出现缺失值
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [32]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [34]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [35]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [36]:
frame2['debt']

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
six      NaN
Name: debt, dtype: object

In [37]:
frame2.debt

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
six      NaN
Name: debt, dtype: object

In [38]:
# 包含字典的嵌套字典
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

## 5.1.3 索引对象

In [39]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [40]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

# 5.2 基本功能

## 5.2.1 重建索引

In [2]:
# reindex 是 pandas 对象的重要方法，该方法用于创建一个符合新索引的新对象
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [3]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [4]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index = [0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [5]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [8]:
# 在 DataFrame 中，reindex 可以改变行索引，列索引，也可以同时改变二者，当仅传入一个序列时，结果中的行会重建索引：
frame = pd.DataFrame(np.arange(9).reshape(3,3),
                    index = ['a', 'c', 'd'],
                    columns = ['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [9]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [11]:
# 列可以使用columns关键字重建索引
states = ['Texas', 'Utah', 'California']
frame.reindex(columns = states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

## 5.2.2 轴向上删除条目

In [13]:
# drop 方法返回一个含有指示值或轴向上删除值的新对象
obj = pd.Series(np.arange(5.), index = ['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [14]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [16]:
# 在DataFrame中，索引值可以从轴向上删除
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [17]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [18]:
# 可以通过传递 axis = 1 或 axis = ‘columns’来从列中删除值
data.drop('two', axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

## 5.2.3 索引、选择与过滤

In [20]:
obj = pd.Series(np.arange(4.), index = ['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [21]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### 5.2.3.1 使用Ioc和iloc选择数据

In [22]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [23]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [24]:
data.iloc[2,[3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [25]:
data.loc[:'Utah']

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11

In [26]:
data.loc[:'Utah','two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

In [27]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

## 5.2.4 整数索引

## 5.2.5 算术和数据对齐 

In [28]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [29]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [30]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [31]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [32]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [33]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

### 5.2.5.1 使用填充值的算术方法

### 5.2.5.2 DataFrame 和 Series 间的操作

In [35]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [36]:
arr[0]

array([0., 1., 2., 3.])

In [37]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [41]:
frame = pd.DataFrame(np.arange(12.).reshape(4, 3), columns = list('bde'), index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [43]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [44]:
# 默认情况下，DataFrame 和 Series 的数学操作中会将 Series 的索引和 DataFrame 的列进行匹配，并广播到各行
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [45]:
# 如果一个索引值不在 DataFrame 的列中，也不在 Series 的索引中，则对象会重建索引并形成联合：
series2 = pd.Series(range(3), index = list('bef'))
series2

b    0
e    1
f    2
dtype: int64

In [46]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [48]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

## 5.2.6 函数应用和映射

In [49]:
frame = pd.DataFrame(np.random.randn(4,3), columns = list('bde'), index = ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah   -0.267410  1.294743 -2.079524
Ohio    1.015603 -1.244352  1.198717
Texas  -0.221028  2.063977  0.517930
Oregon -0.541742  0.109569  0.017761

In [50]:
frame.abs()

b         d         e
Utah    0.267410  1.294743  2.079524
Ohio    1.015603  1.244352  1.198717
Texas   0.221028  2.063977  0.517930
Oregon  0.541742  0.109569  0.017761

In [51]:
# 传递给 apply 的函数并不一定要返回一个标量值，也可以返回带有多个值的 Series
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
frame.apply(f)

b         d         e
min -0.541742 -1.244352 -2.079524
max  1.015603  2.063977  1.198717

In [52]:
frame.apply(f, axis='columns')

min       max
Utah   -2.079524  1.294743
Ohio   -1.244352  1.198717
Texas  -0.221028  2.063977
Oregon -0.541742  0.109569

In [53]:
format = lambda x: '%.2f' % x
frame.applymap(format)

b      d      e
Utah    -0.27   1.29  -2.08
Ohio     1.02  -1.24   1.20
Texas   -0.22   2.06   0.52
Oregon  -0.54   0.11   0.02

## 5.2.7 排序和排名

In [54]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [55]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [57]:
# DataFrame 中，你可以在各个轴上按索引排序
frame = pd.DataFrame(np.arange(8).reshape(2,4), columns = list('dabc'), index = ['three', 'one'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [58]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [59]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [60]:
# 数值默认会升序排序，也可按照降序排序
frame.sort_index(axis = 1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [61]:
# 若要根据 Series 的值进行排序，使用 sort_values 的方法
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [62]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [63]:
frame = pd.DataFrame({'b':[4, 7, -3, 2], 'a':[0, 1, 0, -1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2 -1

In [64]:
frame.sort_values(by = 'b')

b  a
2 -3  0
3  2 -1
0  4  0
1  7  1

In [65]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [66]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [68]:
# DataFrame 可以对行或列计算排名
frame = pd.DataFrame({'b':[4.3, 7.0, -3.0, 2.0], 'a':[0, 1, 0, -1], 'c':[-2.0, 5.0, 8.0, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0 -1 -2.5

In [69]:
frame.rank()

b    a    c
0  3.0  2.5  2.0
1  4.0  4.0  3.0
2  1.0  2.5  4.0
3  2.0  1.0  1.0

In [70]:
frame.rank(axis = 'columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

## 5.2.8 含有重复标签的轴索引

In [71]:
# 考虑一个小型的带有重复索引的Series:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

# 5.3 描述性统计的概率与计算

In [72]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index=['a', 'b', 'c', 'd'], columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [73]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [74]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [75]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [76]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [77]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

## 5.3.1 相关性和协方差

## 5.3.2 唯一值、计数和成员属性

In [78]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [79]:
obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

In [80]:
# value_counts 计算 Series 包含的值的个数
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [81]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [83]:
mask = obj.isin(['b', 'c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [84]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [85]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [86]:
# 计算 DataFrame 多个相关列的直方图
data = pd.DataFrame({'Qu1':[1, 3, 4, 3, 4], 
                     'Qu2':[2, 3, 1, 2, 3],
                     'Qu3':[1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [91]:
result = data.apply(pd.value_counts).fillna(0)
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0