# 7.1 处理缺失值

In [2]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [3]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [6]:
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [8]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna()
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [9]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [10]:
data.dropna(how = 'all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [11]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [12]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [13]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0 -1.436886       NaN       NaN
1 -0.567197       NaN       NaN
2  0.109070       NaN -1.074850
3  0.725593       NaN -0.272739
4  1.835063  1.023805 -1.412475
5 -0.422429  0.839583  0.545828
6 -0.369694  0.298211  1.103973

In [14]:
df.dropna()

0         1         2
4  1.835063  1.023805 -1.412475
5 -0.422429  0.839583  0.545828
6 -0.369694  0.298211  1.103973

In [15]:
df.dropna(thresh=2)

0         1         2
2  0.109070       NaN -1.074850
3  0.725593       NaN -0.272739
4  1.835063  1.023805 -1.412475
5 -0.422429  0.839583  0.545828
6 -0.369694  0.298211  1.103973

## 7.1.2 补全缺失值

In [16]:
df.fillna(0)

0         1         2
0 -1.436886  0.000000  0.000000
1 -0.567197  0.000000  0.000000
2  0.109070  0.000000 -1.074850
3  0.725593  0.000000 -0.272739
4  1.835063  1.023805 -1.412475
5 -0.422429  0.839583  0.545828
6 -0.369694  0.298211  1.103973

In [17]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -1.436886  0.500000  0.000000
1 -0.567197  0.500000  0.000000
2  0.109070  0.500000 -1.074850
3  0.725593  0.500000 -0.272739
4  1.835063  1.023805 -1.412475
5 -0.422429  0.839583  0.545828
6 -0.369694  0.298211  1.103973

In [19]:
_ = df.fillna(0, inplace = True)
df

0         1         2
0 -1.436886  0.000000  0.000000
1 -0.567197  0.000000  0.000000
2  0.109070  0.000000 -1.074850
3  0.725593  0.000000 -0.272739
4  1.835063  1.023805 -1.412475
5 -0.422429  0.839583  0.545828
6 -0.369694  0.298211  1.103973

In [20]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

0        1         2
0 -0.380217 -1.13078  1.861565
1  0.497339  0.17460 -0.136666
2  0.253149      NaN  0.366081
3 -0.906873      NaN -1.778195
4  0.213370      NaN       NaN
5  0.946397      NaN       NaN

In [21]:
df.fillna(method = 'ffill')

0        1         2
0 -0.380217 -1.13078  1.861565
1  0.497339  0.17460 -0.136666
2  0.253149  0.17460  0.366081
3 -0.906873  0.17460 -1.778195
4  0.213370  0.17460 -1.778195
5  0.946397  0.17460 -1.778195

In [23]:
df.fillna(method='ffill', limit=2)

0        1         2
0 -0.380217 -1.13078  1.861565
1  0.497339  0.17460 -0.136666
2  0.253149  0.17460  0.366081
3 -0.906873  0.17460 -1.778195
4  0.213370      NaN -1.778195
5  0.946397      NaN -1.778195

In [24]:
data = pd.Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

# 7.2 数据转换

## 7.2.1 删除重复值

In [25]:
data = pd.DataFrame({'k1':['one', 'two'] * 3 + ['two'], 
                    'k2':[1, 1, 2, 3, 3, 4, 4]})
data


k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [26]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [27]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [28]:
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [29]:
data.drop_duplicates()

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [30]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

## 7.2.2 使用函数或映射进行数据转换

## 7.2.3 替代值

In [32]:
data = pd.Series([1., -999., 2.,-999.,  -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [33]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [34]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [35]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [36]:
# 参数也可以通过字典传递
data.replace({-999:np.nan, -1000:0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

## 7.2.4 重命名轴索引

In [37]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                   index=['Ohio', 'Colorado', 'New York'],
                   columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [38]:
transform = lambda x: x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [39]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [40]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [41]:
# rename可以结合字典型对象使用，为轴标签的子集提供新的值
data.rename(index={'OHIO':'INDIANA'},
           columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [43]:
data.rename(index = {'OHIO':'INDIANA'},
           inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

## 7.2.5 离散化和分箱

In [44]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [46]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [47]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [49]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [51]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [52]:
pd.value_counts(pd.cut(ages, bins, labels=group_names))

Youth         5
MiddleAged    3
YoungAdult    3
Senior        1
dtype: int64

In [54]:
data = np.random.randn(20)
data

array([-0.66144366, -0.44324002, -1.17437315, -1.22432376, -1.07970436,
        1.33230297,  0.71730672,  0.75215229,  1.21581055, -0.15835841,
       -0.6621909 , -0.96993769, -0.21310417, -1.25575723, -0.51427183,
        0.23440346,  0.99177651,  1.28917479, -0.42834195, -0.74831361])

In [55]:
pd.cut(data, 2, precision=2)

[(-1.26, 0.038], (-1.26, 0.038], (-1.26, 0.038], (-1.26, 0.038], (-1.26, 0.038], ..., (0.038, 1.33], (0.038, 1.33], (0.038, 1.33], (-1.26, 0.038], (-1.26, 0.038]]
Length: 20
Categories (2, interval[float64]): [(-1.26, 0.038] < (0.038, 1.33]]

In [56]:
data = np.random.randn(1000)
cats = pd.qcut(data, 4)
cats

[(-0.688, -0.0451], (-0.0451, 0.624], (0.624, 3.912], (-0.0451, 0.624], (-0.0451, 0.624], ..., (-0.0451, 0.624], (0.624, 3.912], (-3.0029999999999997, -0.688], (-0.688, -0.0451], (0.624, 3.912]]
Length: 1000
Categories (4, interval[float64]): [(-3.0029999999999997, -0.688] < (-0.688, -0.0451] < (-0.0451, 0.624] < (0.624, 3.912]]

In [59]:
pd.value_counts(cats)

(0.624, 3.912]                   250
(-0.0451, 0.624]                 250
(-0.688, -0.0451]                250
(-3.0029999999999997, -0.688]    250
dtype: int64

In [60]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-1.228, -0.0451], (-0.0451, 1.247], (-0.0451, 1.247], (-0.0451, 1.247], (-0.0451, 1.247], ..., (-0.0451, 1.247], (1.247, 3.912], (-1.228, -0.0451], (-1.228, -0.0451], (-0.0451, 1.247]]
Length: 1000
Categories (4, interval[float64]): [(-3.0029999999999997, -1.228] < (-1.228, -0.0451] < (-0.0451, 1.247] < (1.247, 3.912]]

In [61]:
pd.value_counts(pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]))

(-0.0451, 1.247]                 400
(-1.228, -0.0451]                400
(1.247, 3.912]                   100
(-3.0029999999999997, -1.228]    100
dtype: int64

## 7.2.6 检测和过滤异常值

In [62]:
data = pd.DataFrame(np.random.randn(10,4))
data

0         1         2         3
0  1.286489  1.397865 -0.946037  0.811722
1 -0.083551 -1.374972  0.935068 -1.001453
2  0.805337 -0.421663 -0.181888  1.760845
3  0.371989 -1.842784 -0.210480  0.194695
4  0.262316 -0.152282 -0.465973  0.824134
5 -0.236822 -0.288523  0.168019  0.252188
6  0.326157  0.248240  0.033218  1.319126
7  1.111331 -0.984994  0.414176  0.641746
8 -0.535496  1.560436  0.257204 -1.688310
9  0.050980 -0.495640  1.138580  1.436486

In [63]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.001457     0.033408    -0.015227    -0.003943
std       1.021181     0.991296     1.033075     0.983199
min      -3.456862    -2.957995    -3.562991    -3.261692
25%      -0.659360    -0.688787    -0.716346    -0.659253
50%       0.023453    -0.026895    -0.016686    -0.002852
75%       0.707993     0.679003     0.650054     0.639706
max       3.151642     3.470267     3.039384     3.981617

In [64]:
# 找出一列中绝对值大于3的值
col = data[2]
col[np.abs(col) > 3]

18    -3.562991
219    3.039384
622   -3.013124
Name: 2, dtype: float64

In [66]:
# 要选出所有值大于3或小于-3的行，可以对布尔值DataFrame使用any方法：
data[(np.abs(data)>3).any(1)]

0         1         2         3
18   0.157791 -0.169451 -3.562991  1.482082
66  -3.069954 -0.622433 -0.212838  1.003738
219 -1.743451  0.775279  3.039384  0.057053
236 -1.493543 -1.130171  0.750636  3.293547
239 -3.456862  0.455222 -0.171454 -1.006502
622 -2.329712  1.116853 -3.013124  0.515702
661  0.749243 -0.442431  0.932013  3.388587
776  3.151642 -1.489593  0.765943 -0.608870
877  0.237180 -0.709724 -1.481930 -3.261692
885  0.958935  3.280357 -0.533083  0.445483
956 -3.418175  0.205216  0.604360  0.167149
964  0.185329 -0.104331  0.114841  3.981617
982  0.200758  3.470267 -1.067443  0.970911

## 7.2.7 置换和随机抽样

In [68]:
df = pd.DataFrame(np.arange(5*4).reshape((5,4)))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [70]:
sampler = np.random.permutation(5)
sampler

array([1, 4, 0, 2, 3])

In [72]:
# 整数数组可以用在基于iloc的索引或等价的take函数中
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [74]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
4  16  17  18  19
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15

In [77]:
choices = pd.Series([5, -7, -1, 6, 4])
choices

0    5
1   -7
2   -1
3    6
4    4
dtype: int64

In [78]:
draws = choices.sample(n=10, replace=True)
draws

1   -7
1   -7
2   -1
1   -7
1   -7
2   -1
1   -7
0    5
2   -1
0    5
dtype: int64

## 7.2.8 计算指标/虚拟变量

In [80]:
df = pd.DataFrame({'key':['b', 'b', 'a', 'c', 'a', 'b'], 'data1':range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [81]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [82]:
# 将get_dummies与cut等离散化函数结合使用是统计应用的一个有用方法
np.random.seed(12345)
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [83]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

# 7.3 字符串操作

## 7.3.1 字符串对象方法

In [88]:
val = 'a, b, guido'
val.split(',')

['a', ' b', ' guido']

In [87]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [90]:
first, second, third = pieces
first+'::'+second+'::'+third

'a::b::guido'

In [91]:
'##'.join(pieces)

'a##b##guido'

In [92]:
'guido' in val

True

In [93]:
val.index(',')

1

In [94]:
val.index('a')

0

In [95]:
val.index('b')

3

In [96]:
val.index(' ')

2

In [97]:
val.find('#')

-1

## 7.3.2 正则表达式

In [102]:
# 正则表达式提供了一种在文本中灵活查找或匹配字符串模式的方法
# 假设我们想将含有多种空白字符（）的字符串拆分开
import re
text = "foo    bar\t baz   \tqux"
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [103]:
regex = re.compile('\s+')

## 7.3.3 pandas 中的向量化字符串函数

In [104]:
data = {'Dave':'dave@google.com',
       'Steve':'steve@gmail.com',
       'Rob':'rob@gmail.com',
       'Wes':np.nan}
data

{'Dave': 'dave@google.com',
 'Steve': 'steve@gmail.com',
 'Rob': 'rob@gmail.com',
 'Wes': nan}

In [105]:
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [107]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [108]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [109]:
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
pattern

'[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,4}'

In [110]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [dave@google.com]
Steve    [steve@gmail.com]
Rob        [rob@gmail.com]
Wes                    NaN
dtype: object